version: '3'

services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./UML.ipynb:/app/UML.ipynb
      - ./kaggle/input/google-quest-challenge :/app/kaggle/input/google-quest-challenge
